image:
  repository: kong/kong-gateway
  tag: "3.7.0.0"

env:
  role: data_plane
  database: "off"
  cluster_mtls: pki
  cluster_telemetry_endpoint: "telemetry.konghq.com:443"
  cluster_control_plane: "control.konghq.com:443"
  cluster_server_name: "control.konghq.com"
  cluster_telemetry_server_name: "telemetry.konghq.com"
  lua_ssl_trusted_certificate: system
  trusted_ips: "0.0.0.0/0,::/0"
  real_ip_header: "X-Forwarded-For"
  real_ip_recursive: "on"

secretVolumes:
  - kong-cluster-cert

ingressController:
  enabled: false
  installCRDs: false

proxy:
  enabled: true
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 70
